import { AtSign, UserPlus, MessageCircle, Search, Smartphone, Globe } from 'lucide-react';
import MarketingLanding from '../../components/seo/MarketingLanding';

const faqs = [
  { q: 'What is username-based chat?', a: 'Username-based chat lets people identify and discover accounts through a username or profile identity instead of relying only on a saved phone contact.' },
  { q: 'Why use a username?', a: 'A username can be easier to share across platforms and can help separate your public profile identity from your phone contacts.' },
  { q: 'Can I chat from a browser?', a: 'VoiceID offers a browser-based experience on supported devices. Features depend on sign-in and account permissions.' },
  { q: 'Can I control who I interact with?', a: 'Use the available profile, contact and account controls, and review requests before accepting them.' },
];

export default function UsernameChatPage() {
  return <MarketingLanding path="/username-chat" breadcrumbLabel="Username Chat" seoTitle="Username Chat App — Connect Through Your VoiceID" metaDescription="Discover username-based chat with VoiceID. Find people through profile identities and continue conversations across supported devices." keywords="username chat app, chat by username, social messaging username, find people by username, profile based chat" h1="Chat Through Your Username" intro="Make your digital identity easier to share with a username-based social messaging experience." benefits={[{ icon: AtSign, title: 'Share a Username', description: 'Use a recognizable username as part of your VoiceID profile identity.' }, { icon: UserPlus, title: 'Connect With People', description: 'Use available discovery and contact flows to connect with other users.' }, { icon: MessageCircle, title: 'Message in One Place', description: 'Continue conversations with text, voice and other supported messaging features.' }, { icon: Search, title: 'Discover Profiles', description: 'Find relevant profiles through the discovery tools available in VoiceID.' }, { icon: Smartphone, title: 'Mobile Ready', description: 'Access your account from supported mobile devices and browsers.' }, { icon: Globe, title: 'Share Across Platforms', description: 'A username can be easier to share than a long contact detail when introducing your profile.' }]} howItWorks={[{ title: 'Choose your identity', description: 'Create or configure your VoiceID username during the account flow.' }, { title: 'Complete your profile', description: 'Add profile information that helps people recognize you.' }, { title: 'Find and connect', description: 'Use discovery and contact features to start conversations.' }]} faqs={faqs} relatedLinks={[{ label: 'Private Chat', path: '/private-chat' }, { label: 'Online Chat', path: '/online-chat' }, { label: 'Browser Chat', path: '/browser-chat' }]} />;
}
