import { Mic, Users, Radio, Star, Calendar, MessageCircle } from 'lucide-react';
import MarketingLanding from '../../components/seo/MarketingLanding';

const faqs = [
  { q: 'What are creator voice rooms?', a: 'Creator voice rooms are conversation spaces that creators can use for discussions, community interaction and live participation.' },
  { q: 'Who can create a room?', a: 'Room creation depends on the permissions and creator features enabled for your VoiceID account.' },
  { q: 'Can listeners participate?', a: 'Participation depends on the room host settings. Some rooms may allow listeners to request or receive speaking access.' },
  { q: 'Can I use rooms from a phone?', a: 'Supported mobile browsers can access compatible room features, subject to device and microphone permissions.' },
];

export default function VoiceRoomsForCreatorsPage() {
  return <MarketingLanding path="/creator-voice-rooms" breadcrumbLabel="Creator Voice Rooms" seoTitle="Creator Voice Rooms — Build Community on VoiceID" metaDescription="Use VoiceID creator voice rooms to host conversations, connect with listeners and build an engaged community." keywords="creator voice rooms, live audio community, host voice room, creator chat app, live discussion rooms" h1="Create Voice Spaces Your Community Enjoys" intro="Bring your audience together for conversations, questions and shared moments through creator-focused voice rooms." benefits={[{ icon: Mic, title: 'Host Conversations', description: 'Use voice rooms for discussions, Q&A sessions and community interaction.' }, { icon: Users, title: 'Build Community', description: 'Give people a place to return to and connect around a shared interest.' }, { icon: Radio, title: 'Live Participation', description: 'Use room controls to manage who can speak and how the conversation flows.' }, { icon: Star, title: 'Creator Identity', description: 'Present your creator profile and make it easier for people to recognize your content.' }, { icon: Calendar, title: 'Plan Sessions', description: 'Prepare topics and recurring ideas for more consistent community activity.' }, { icon: MessageCircle, title: 'Continue After Live', description: 'Use messaging and related features to keep conversations going.' }]} howItWorks={[{ title: 'Set up your profile', description: 'Complete your VoiceID profile so your community can recognize you.' }, { title: 'Create or manage a room', description: 'Use the available room tools and configure participation settings.' }, { title: 'Invite your community', description: 'Share the room through your existing audience channels and start the conversation.' }]} faqs={faqs} relatedLinks={[{ label: 'Group Voice Chat', path: '/group-voice-chat' }, { label: 'Features', path: '/features' }, { label: 'About VoiceID', path: '/about' }]} />;
}
